### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by Wonovan** [arjankuijpers/SpotifyRemote#1]
I can't seem to find where to access the commands. Some documentation on how to use / configure it would be helpful.

**Comment by arjankuijpers** [comment]
I will provide it very soon.

**Comment by arjankuijpers** [comment]
I found out that there is a naming error, in the view context menu. 
Where the menu is called Test Menu. I will release a new version shortly that fixes this.

**Comment by arjankuijpers** [comment]
I finshed first version of the Readme, and added an Installation section which describes how to install and enable the extension. 

Is this issue fixed ?
if not please respond in an appropriate amount of time, otherwise I will close the issue 👍
