### ISSUE TITLE
Stop VS

### ISSUE THREAD

**Issue by 404d6** [arjankuijpers/SpotifyRemote#10]
The message: No se pudieron rellenar automáticamente las cuentas de Visual Studio Team Services.
    
Se detectó el error siguiente: TF400813: Resource not available for anonymous access. Client authentication required.

![00001](https://user-images.githubusercontent.com/19860167/31559560-ab26abf0-b016-11e7-8d10-ac3cf9784d9b.PNG)

**Comment by arjankuijpers** [comment]
Thanks for your report.

This seems like a crash that happens when retrieving the playlists.

**Comment by arjankuijpers** [comment]
I have debugged the issue, seems like it occurs when trying to use `spotWeb = new SpotifyWebAPI();`
even if it fails authentication. 
Will commit bug fix soon after testing.

**Comment by arjankuijpers** [comment]
Please check out the release 2.0.0 branch: [commit 4f33703d](https://github.com/arjankuijpers/SpotifyRemote/commit/4f33703d73258aab2c6a9a782abd2b3e5ce9c6d0) should be stable, you can build and install it, and should provide you with the basics of SpotifyRemote.
Although some features are missing it, it way more stable then v1.1.x

**Comment by arjankuijpers** [comment]
I consider this issue closed because of Version 2.0.0 is stable and no longer cause crashes.
