### ISSUE TITLE
Playlist duplication

### ISSUE THREAD

**Issue by dopeldead** [arjankuijpers/SpotifyRemote#11]
In VS 2017, when I open the playlist panel I got my playlist, if I close this panel and reopen it every playlist is there twice 

For exemple if i have Playlist_A, Playlist_B, Playlist_C at first 

I'll get  Playlist_A, Playlist_B, Playlist_C , Playlist_A, Playlist_B, Playlist_C on second opening.

And so on...

**Comment by arjankuijpers** [comment]
Thanks for the report, I will look into it.
