### ISSUE TITLE
No option to install to Visual Studio 2017

### ISSUE THREAD

**Issue by xmendoza** [arjankuijpers/SpotifyRemote#5]
Installing to Visual Studio 2015 is the only option for me

**Comment by arjankuijpers** [comment]
Thanks for your report, will be fixed next update.
Duplicate of:  https://github.com/arjankuijpers/SpotifyRemote/issues/7

**Comment by arjankuijpers** [comment]
This issue is fixed. Please let me know if you still have issues installing for Visual Studio 2017.
