### ISSUE TITLE
Will not install on Windows 10, Visual Studio 2017 box

### ISSUE THREAD

**Issue by DoScuba** [arjankuijpers/SpotifyRemote#7]
I have Visual Studio 2017 and Spotify installed.

Some of the log message...
Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.

5/18/2017 2:55:03 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/18/2017 2:55:03 PM - Found installed product - Global Location
5/18/2017 2:55:03 PM - Found installed product - Visual Studio Professional 2017
5/18/2017 2:55:03 PM - Found installed product - Visual Studio Team Explorer 2017 (2)
5/18/2017 2:55:03 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by arjankuijpers** [comment]
Thanks for your report, will be fixed next update.

**Comment by arjankuijpers** [comment]
This issue is fixed. Please let me know if you still have issues installing for Visual Studio 2017.

**Comment by DoScuba** [comment]
Awesome!!  Works like a charm!  Thank you!
