### ISSUE TITLE
SpotifyRemoteSettings panel unreadable if using a light VS2017 theme

### ISSUE THREAD

**Issue by MikeStacey-Gee** [arjankuijpers/SpotifyRemote#8]
![spotifyremotesettingspanelunreadable](https://user-images.githubusercontent.com/16876749/28323204-0975d70c-6bd0-11e7-8254-ddbb9f6c3935.png)

**Comment by arjankuijpers** [comment]
Thanks for your report, I am working on a fix.
Sorry for the inconvenience.

**Comment by arjankuijpers** [comment]
The issue has been fixed, and I have released a new version including the fix.

https://github.com/arjankuijpers/SpotifyRemote/releases/tag/Release_v1.1.0
You should be able to download it through the Visual Studio Marketplace as well.
Look out for version v1.1.0, let me know if you have questions or remarks.
Feel free to re-open the issue, if you need to.
